### ISSUE TITLE
Setting up documentation

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pylammpsmpi#14]
@jan-janssen We should also think about setting up some documentation. My opinion is to go with readthedocs. What do you think?

**Comment by jan-janssen** [comment]
Readthedocs is perfect, we also use it for pyiron now https://pyiron.readthedocs.io/en/latest/

**Comment by jan-janssen** [comment]
I created the readthedocs link https://pylammpsmpi.readthedocs.io/en/latest/ - without content so far.

**Comment by srmnitc** [comment]
Could you add me as maintainer on readthedocs?

**Comment by jan-janssen** [comment]
Done

**Comment by srmnitc** [comment]
Documentation is set up. It is served now from docs branch, but I will make a pull request now and set it to build from master

**Comment by srmnitc** [comment]
Documentation seems to be building ok. We can improve it as we go along. The theme is a bit different,the one I used for pyscal, but we can put it back if you wish.
