### ISSUE TITLE
New version 0.2.3 is not installed

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pylammpsmpi#142]
The import error with ´RaisingThread´ persists as the new version 0.2.3 is not installed by conda. When trying to install, it complains that a compatible LAMMPS version could not be found. On debugging a bi, lammps complained about libcurl version, libcurl about krb5, krb5 about pyqt where I stopped.

I am not sure what the solution is.

**Comment by jan-janssen** [comment]
Is this specific to `cmti001` or a general issue? For me the installation worked fine and also the continuous integration works fine.

**Comment by srmnitc** [comment]
On a clean env on my workstation, it worked fine. So maybe one of the existing packages were causing the conflict. I will go ahead and close this issue.
