### ISSUE TITLE
socket connection stuck

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pylammpsmpi#22]
When using socket as communicator, the creation of the object seems to get stuck on
```hostsocket, _ = s.accept()``` - Line 85 from `communicate.py`

**Comment by jan-janssen** [comment]
Yes, I did not have the time to test it yet.

**Comment by jan-janssen** [comment]
Btw. Are you at ICAMS today?

**Comment by srmnitc** [comment]
I am not now, I am working from home nowadays. But I will come around 13.00 - I have meetings from 14.00

**Comment by srmnitc** [comment]
Are you around?

**Comment by jan-janssen** [comment]
We have a PhD defense today, that is why I am at ICAMS, but I do not think I am going to stay till 13:00 - so maybe it is easier to meet another day.

**Comment by srmnitc** [comment]
Yeah, I do not think I will be able to make it before that. Let's meet another day then!

**Comment by jan-janssen** [comment]
Ok, I get the point why it is not working - it is basically waiting for the connection of the client before it continuous.

**Comment by jan-janssen** [comment]
I tired to separate the connect part - https://github.com/pyiron/pylammpsmpi/commit/1f25daef8a7b4c997de38dcc4f8719cdf73a22c0

**Comment by srmnitc** [comment]
A little bit busy with some other things - I will contribute more soon! sorry!

**Comment by jan-janssen** [comment]
In terms of using higher level libraries and not reinventing the wheel, we should consider using dask for socket communication:
https://distributed.dask.org/en/latest/communications.html

**Comment by srmnitc** [comment]
Yeah, we could play around  with it. I use dask quite a bit in my normal
work. This might also be of interest.
https://distributed.dask.org/en/latest/actors.html

**Comment by srmnitc** [comment]
@jan-janssen A combination of [dask-distributed](https://distributed.dask.org/en/latest/) and [dask-jobqueue](https://jobqueue.dask.org/en/latest/) looks promising. I have started a new branch. It is all clunky at the moment, but when things shape up I will update you.

**Comment by jan-janssen** [comment]
This might even be interesting beyond the Lammps interface, like having a generic interface for connecting to calculators via sockets.

**Comment by srmnitc** [comment]
Yeah, I am super excited to get this working. I went for two workshops organised by ECAM in which they covered dask. I briefly discussed with one of the guys here at Julich. If we need more help, that would also be possible I think. Let us see how it goes.

**Comment by srmnitc** [comment]
#32  is almost ready. Using jobqueue and dask actors, we can run pylammpmpi on queuing systems while being able to interact with it directly from a jupyter notebook. The code has some restructuring, a higher level wrapper is added to convert dask futures to actual values. It also works with the local mode. I have added some example in the form of notebooks in the notebooks folder. One for local cluster and one for slurm. dask-distributed and dask-jobqueue should also be added to dependencies. I have not yet tested extensively, I will be running a couple of projects later on to see how it works out. I think its really cool :)

**Comment by srmnitc** [comment]
Of course this issue would then be closed if we merge #32
