### ISSUE TITLE
Strange problem

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pylammpsmpi#24]
Sorry for the cryptic title, but I seem to have a strange problem. So far, I was the example notebook from the main repo folder, and hence when the subprocess is launched the path of the executable it selects is directly from the repo, for example, like `/pylammpsmpi/pylammpsmpi/mpi/lmpmpi.py`. In this case, everything works.
Now, when I try with the jupyter notebook in a different folder, the executable path now is somethings like `.conda/envs/p3/lib/python3.6/site-packages/pylammpsmpi-0.post0.dev84-py3.6.egg/pylammpsmpi/mpi/lmpmpi.py`. This is case trying a `lmp.version` throws `EOFError: Ran out of input`. I am trying a couple of things to see what exactly the problem is, but for the moment I am stuck.

**Comment by jan-janssen** [comment]
Are you sure the file is available? lmpmpi? Maybe it is missing because we were missing an init file https://github.com/pyiron/pylammpsmpi/pull/25

**Comment by srmnitc** [comment]
Great! The init file was the problem. Its fixed now. I can confirm everything works. Thanks a lot!
