### ISSUE TITLE
Using commands directly throws error

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pylammpsmpi#27]
Using `lmp.run(1)` instead of  `lmp.command('run 1')` sometimes crashes the subprocess. See #26

**Comment by jan-janssen** [comment]
Do we even have a run command implemented? https://github.com/pyiron/pylammpsmpi/blob/master/pylammpsmpi/mpi/lmpmpi.py#L368

**Comment by srmnitc** [comment]
Yeah, it is just calling the `command` function itself through `__getattr__` - https://github.com/pyiron/pylammpsmpi/blob/master/pylammpsmpi/lammps.py#L37

**Comment by srmnitc** [comment]
In fact, it seems `create_atoms` is the one that does not work as `lmp.create_atoms`

**Comment by jan-janssen** [comment]
Ok, I guess it makes sense to activate the log in the process file just to log what is communicated. But it makes sense that Lammps crashes if the create atoms failed and the run can not be executed without atoms.

**Comment by srmnitc** [comment]
Yeah, thats my any further commands did not work, of course.

**Comment by srmnitc** [comment]
The same happens if you have read in from a file and the file has errors. The subprocess would crash, but on the main file, it would give `BrokenPipe` error

**Comment by jan-janssen** [comment]
We could try to add a general `try except` around the command part and then write the error to a file once an error is raised, just to check if we can catch the error on the Python side.

**Comment by srmnitc** [comment]
Yes, that would work. I will add this. Also `create_atoms` - I understand now - there is already a method called `create_atoms` which was being called instead of command create_atoms. That is why it crashed. We have not yet fixed `create_atoms` method.

**Comment by srmnitc** [comment]
Merging #29 will close this issue.
