### ISSUE TITLE
Waiting until a command is executed

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pylammpsmpi#30]
If a command is run, for example ``lmp.command("minimize 1.e-14 1.e-14 1000000 1000000")``, and then use ``lmp.get_thermo("vol")``, the second command has to be blocked until the minimize is over. This seems to be not happening. Any idea on how we can achieve this @jan-janssen ?

**Comment by jan-janssen** [comment]
Can you confirm the same is happening when you use the lammps library directly?

**Comment by srmnitc** [comment]
Not it does not happen when using lammps library directly.  It is probably because on pylammpsmpi, the command is sent through subprocess, but there is nothing to indicate if the command is executed or not.

**Comment by jan-janssen** [comment]
Then this means we would need a control parameter send back after successful execution of a command.

**Comment by srmnitc** [comment]
Yes, I would think so. Okay I can try to implement this.
