### ISSUE TITLE
Communication with the MPI process

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pylammpsmpi#35]
I just learned about the https://github.com/NCAR/mpirical package, maybe we can use it to remove our own subprocess interface for calling Lammps. Again following the idea to reuse existing code wherever possible.

**Comment by srmnitc** [comment]
oh this looks super interesting! I will take a look. If it works as expected we should definitely remove the subprocess call.

**Comment by jan-janssen** [comment]
Maybe a good way to start would be to create a conda package for `mpirical` - just in case you are interested.

**Comment by srmnitc** [comment]
From the limited documentation they have, it seems it might be a problem to keep the subprocess alive. We would need to keep it alive, of course.

**Comment by jan-janssen** [comment]
Ok, let's close the issue for now. We should just try to keep our eyes open to look for similar packages.
