### ISSUE TITLE
Examples not working 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pylammpsmpi#38]
I tried to execute the examples again and they both get stuck at: 

```
ke = lmp.extract_compute("ke", 1, 1)
len(ke)
```

**Comment by srmnitc** [comment]
This is strange. Seems to work for me. Which example exactly did you run?

**Comment by jan-janssen** [comment]
I tried both` lammps_local` and `lammps_local_cluster` on mybinder and both get stuck at the same point. I am just wondering if I broke something ...

**Comment by srmnitc** [comment]
Ah it seems so. I had not updated my repo. Now it is stuck

**Comment by srmnitc** [comment]
It has a couple of bugs. Seems like `type` is renamed everywhere. I can fix it in a bit.

**Comment by jan-janssen** [comment]
Fixed in https://github.com/pyiron/pylammpsmpi/pull/39

**Comment by jan-janssen** [comment]
Maybe we should also think about some integration test, which directly runs real lammps calculation.

**Comment by srmnitc** [comment]
Ah yes. That would be great. I have a couple of examples that could be useful. I can work on this. Started on #40
