### ISSUE TITLE
Output file locations when submitting to dask cluster

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pylammpsmpi#42]
This problem if specific : Consider a dask cluster created from a notebook located in directory `A`, when lammps simulation is carried out from a notebook in directory `B`, which connects to the cluster created in `A`. The output files - log or traj files are not generated in `B`, but in `A`. Probably the dask cluster needs some kind of output directory. Or, full paths needs to be specified for lammps files.

**Comment by srmnitc** [comment]
This can be fixed easily by using a command such as `os.chdir` to the class before subprocess is started. This ensures that the log, traj files etc will be generated in the folder where the notebook which runs lammps is situated, not where the cluster is started from. Will fix it in the coming days..

**Comment by jan-janssen** [comment]
Should not it be sufficient to define the working_directory in https://github.com/pyiron/pylammpsmpi/blob/master/pylammpsmpi/lammps_wrapper.py#L9 ? This should overwrite the settings provided from DASK.

**Comment by srmnitc** [comment]
Indeed, that seems to be enough! Thanks for pointing it out. Since the option already exists, I am going to go ahead and close the issue. Thanks!
