### ISSUE TITLE
Reporting pylammpsmpi in publications/thesis etc

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pylammpsmpi#43]
Hi @jan-janssen, I have a student who will finish a project which used pylammpsmpi completely for the simulations. Although its not important for the project, I was thinking how in general should one mention pylammpsmpi in publications/thesis etc.

**Comment by jan-janssen** [comment]
That is a good question. I wrote the initial version as part of pyiron so I always thought about it as a wrapper around lammps to make the lammps library accessible via MPI inside pyiron. In particular as pyiron is primarily sequential code while we want to execute the lammps library via MPI. I realise that it uses no pyiron components and can be used independently, so citing pyiron might be a bit confusing for the readers. 

Maybe something like:
```
The calculations were executed using pylammpsmpi[1] which was developed as part of the pyiron project[2]. 

[1]: https://github.com/pyiron/pylammpsmpi
[2]: J. Janssen, et al., Comp. Mat. Sci. 161 (2019) 
```

Finally I am also open to create a separate publication for it, still that would be additional work and I am not sure if it would result in a lot of citations. Or we could try to integrate it into the official lammps release. I plan to present it to them but did not have the time yet.

**Comment by srmnitc** [comment]
I do not think a separate publication is necessary, in the end it is wrapper. For now, I think the above works, but we could also make an archive in zenodo and use that for [1] above. What do you think?

**Comment by jan-janssen** [comment]
I am open for both - I have not used zenodo - but if you want to we can release the current version. In addition we can also create a new release for conda because we did at least a few fixes in the last months.

**Comment by srmnitc** [comment]
I guess we should release the current version. Might be good to have it on zenodo too. Could you make a release please?

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pylammpsmpi/releases/tag/pylammpsmpi-0.0.4

**Comment by srmnitc** [comment]
Zenodo needs access to the repository to create a DOI. For now, I just gave the above citation to the student.
