### ISSUE TITLE
Fix travis 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pylammpsmpi#5]
The tests work locally but somehow they fail on travis.

**Comment by jan-janssen** [comment]
It seems like the Travis tests are not executed since I moved the repository.

**Comment by srmnitc** [comment]
I set up on my fork of the repository to test, it seems that tests fail if you use more than one number of cores. On a single core everything works. That's as far as I got.

**Comment by srmnitc** [comment]
This is necessarily not a fix. But an equivalent github workflow seems to pass all the tests. The reason for travis failing is still unknown to me.
