### ISSUE TITLE
recall variables in python to lammps

### ISSUE THREAD

**Issue by hanfengzhai** [pyiron/pylammpsmpi#77]
Hi there,

I was wondering if it's possible to create a new variable in python and then pass it on to lammps, e.g.,
`from pylammpsmpi import LammpsLibrary
lmp = LammpsLibrary(cores=36)
number = 5
lmp.command("variable        r equal %d" % number)`

Many thank,
HZ

**Comment by jan-janssen** [comment]
Sure - I just tested the commands and they worked fine for me. We try to be compatible to the commands of the Lammps library, so most commands should work out of the box.

**Comment by hanfengzhai** [comment]
Thanks so much Jan :)), I recompiled LAMMPS with Python and it also works for me. I assume the previous `make yes-python` installed the wrong python version for me.

**Comment by jan-janssen** [comment]
The easiest way is to use the lammps conda package: 
```
conda install -c conda-forge lammps
```
This is also what we use to test the compatibility.
