### ISSUE TITLE
pylammpsmpi not running on 2 cores or more

### ISSUE THREAD

**Issue by JB-White** [pyiron/pylammpsmpi#87]
Hey there, I'm trying to get pylammpsmpi up and running on the cluster of my institution. The cluster uses slurm as a resource manager. I installed pylammpsmpi 0.0.9 via pip install. When I try to run the job test script (see below) on one core, it works fine. When I try to run it on two cores or more, it doesn't work. It doesn't seem to be an issue of mpi4py since the test script suggested on the lammps website (https://docs.lammps.org/Python_launch.html) works just fine. I also used different versions of openmpi, but it didn't change anything. Do you have any suggestions for further troubleshooting?

The test script looks like this:
```
from pylammpsmpi import LammpsLibrary

lmp = LammpsLibrary(cores=2, mode='local')
print(f"LAMMPS version: {lmp.version}")
lmp.file("crn.in")
lmp.command("fix 2 all npt temp 300.0 300.0 100.0 iso 100.0 100.0 100.0")
lmp.command("run 1")
print("test2")
```

And the output like this:
```
Traceback (most recent call last):
  File "/work/smjbweis/Programs/may22/lib/python3.9/site-packages/pylammpsmpi/utils/../mpi/lmpmpi.py", line 466, in <module>
    input_dict = pickle.load(sys.stdin.buffer)
EOFError: Ran out of input
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[64109,1],1]
  Exit code:    1
--------------------------------------------------------------------------
LAMMPS version: 20210929
Traceback (most recent call last):
  File "/work/smjbweis/hrmc_files/hrmc_eg_zif4_TCN210622/./test.py", line 5, in <module>
    lmp.file("crn.in")
  File "/work/smjbweis/Programs/may22/lib/python3.9/site-packages/pylammpsmpi/lammps_wrapper.py", line 73, in func_wrapper
    fut = func(*args, **kwargs)
  File "/work/smjbweis/Programs/may22/lib/python3.9/site-packages/pylammpsmpi/utils/lammps.py", line 119, in file
    _ = self._receive()
  File "/work/smjbweis/Programs/may22/lib/python3.9/site-packages/pylammpsmpi/utils/lammps.py", line 83, in _receive
    output = pickle.load(self._process.stdout)
EOFError: Ran out of input
Exception ignored in: <function LammpsBase.__del__ at 0x2b65ff7b5550>
Traceback (most recent call last):
  File "/work/smjbweis/Programs/may22/lib/python3.9/site-packages/pylammpsmpi/utils/lammps.py", line 677, in __del__
  File "/work/smjbweis/Programs/may22/lib/python3.9/site-packages/pylammpsmpi/utils/lammps.py", line 667, in close
  File "/work/smjbweis/Programs/may22/lib/python3.9/site-packages/pylammpsmpi/utils/lammps.py", line 68, in _send
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by jan-janssen** [comment]
pylammpsmpi in the background is calls `mpiexec`. https://github.com/pyiron/pylammpsmpi/blob/master/pylammpsmpi/utils/lammps.py#L34 So one thing to check is that `which mpiexec` returns the same path as `which mpirun`. Both should point to the `openmpi` version you used to compile the Lammps library. While the examples on the LAMMPS website also work with `mpich` pylammpsmpi is communicating with the parallel process via standard input and standard output, which is currently only supported by `oepnmpi` as `mpich` has a character limit on the the standard input. I hope this helps.

**Comment by JB-White** [comment]
Thanks for the suggestion. Both commands are returning the same directory of the openmpi version I'm using:

/cluster/sfw/openmpi/gcc4.8.x/4.1.1/mpi_thread_multiple/bin/mpiexec
/cluster/sfw/openmpi/gcc4.8.x/4.1.1/mpi_thread_multiple/bin/mpirun

This is the case regardless of whether I run the job on 1 or 2 cores.

**Comment by jan-janssen** [comment]
I created a quick mybinder example to demonstrate how `pylammpsmpi` works with the conda packages of `openmpi`, `pylammpsmpi` and `lammps`. https://github.com/jan-janssen/pylammpsmpi-example . Can you check if this example with the corresponding conda packages works on your system? Once the example works on your system, then you can replace one component at a time to check which dependency is breaking `pylammpsmpi`.
